#!/usr/bin/env node

'use strict';

var swig = require('swig');
var fs = require('fs');
var fileHelper = require('./file-helper');
var docBlocks = require('./doc-blocks');
var util = require('./util');
var path = require('path');
var fs = require('fs');

// global settings
var settings = {};

/**
* @name init
* @description Initialize global settings.  This is done automatically,
* but you can call it again in case you screwed something up.
* @public
*/
var init = function () {

    var rc;

    // set defaults
    settings = {
        docBlockRegex: /\/\*{2,}(.|[\r\n])+?\*\//g,
        extensions: ['js'],
        include: [],
        exclude: ['node_modules', 'test'],
        outputFile: 'README.md'
    };

    // check for .whatsupdocrc
    try {
        rc = fs.readFileSync(path.join(process.cwd(), '.whatsupdocrc'), 'utf-8');
        
    } catch (e) {
        console.log(e);
        console.log('no config file');
    }

    if (rc) {
        try {
            rc = JSON.parse(rc);
        } catch (e) {
            throw new Error('.whatsupdocrc JSON is invalid');
        }
    }
};

/**
* @description generate the API docs
* @method go
* @param {String} [directory = process.cwd()]
* @public
*/
var go = function (directory) {
    
    var files, blocks, result;

    init();
    
    // find the files
    files = fileHelper.getFiles(directory, null, true).files;

    // find the blocks in each
    blocks = getBlocksFromFiles(files);

    blocks = groupBlocks(blocks);

    result = stringify(blocks);

    writeResults(result);
};

/**
* @name writeResults
* @description Writes the api doc string into the
* destination file.
* @param {String} results
* @private
*/
var writeResults = function (results) {
    var destinationFile = path.join(process.cwd(), settings.outputFile);
    var destinationText = fileHelper.readFileSync(destinationFile);
    var newText = insertDocs(destinationText, results);
    fs.writeFileSync(destinationFile, newText);
};

/**
* @name insertDocs
* @description Inserts docs at the proper place into another string.
* This will replace old docs if found.
* @param {String} target the string docs will be inserted into
* @param {String} docs
* @return {String} updated the updated target 
* @private
*/
var insertDocs = function (target, docs) {
    var regex = /<!--- whatsupdoc-start(\n|.)+whatsupdoc-end -->\n/g;

    if (regex.test(target)) {
        target = target.replace(regex, docs);
    } else {
        target += docs;
    }

    return target;
};

/**
* @name groupBlocks
* @description group blocks by privacy
* @param {DocBlock[]} blocks
* @return {Object}
*/
var groupBlocks = function (blocks) {
    var grouped = {
        'public': [],
        'protected': [],
        'private': [],
        '': []
    };

    util.each(blocks, function (block) {
        var which = '';

        if (block.public) {
            which = 'public';
        } else if (block.protected) {
            which = 'protected';
        } else if (block.private) {
            which = 'private';
        }

        grouped[which].push(block);
    });

    return grouped;
};

/**
* @description get the DocBlocks from an Array of files
* @function getBlocksFromFiles
* @param {String[]} filePaths
* @return {DocBlock[]}
* @private
*/
var getBlocksFromFiles = function (filePaths) {
    var i, max, result = [];

    var getBlocks = function (rawBlocks, filePath) {
        var blocks = [];

        util.each(rawBlocks, function (block, i) {
            blocks.push(
                new docBlocks.DocBlock(block, filePath)
            );
        });

        return blocks;
    };

    util.each(filePaths, function (filePath) {
        var rawBlocks = fileHelper.getMatches(filePath, settings.docBlockRegex);

        result = result.concat(getBlocks(rawBlocks, filePath));
    });

    return result;
};

/**
* @description get the result of bunch of
* stringified DocBlocks
* @function stringify
* @param {Object} groupedBlocks
* @return {String}
* @private
*/
var stringify = function (groupedBlocks) {
    var result = '';

    util.each(groupedBlocks, function (blocks, privacy) {
        var str = '';

        util.each(blocks, function (block) {
            str += block.stringify();
        });

        groupedBlocks[privacy] = str;
    });

    // Now that we've got each group stringified, load up
    // the main template.

    var templateFilePath = path.join(__dirname, 'template.txt');
    var template = swig.compileFile(templateFilePath);

    groupedBlocks.foo = 'hello';

    return template({
        'private': groupedBlocks.private,
        'protected': groupedBlocks.protected,
        'public': groupedBlocks.public,
        '': groupedBlocks['']
    });
};

/**
* @name configure
* @description Get/set global settings.  If no args, return all settings.
* If just name, return that setting.  If name & value, set that setting.
* @param {String/Object} [name] setting name - Optionally pass a an Object
* to set multiple values at once.
* @param [value]
* @public value setting value
* @return {Object/String/Number/Boolean} setting Depending on what args
* were passed, this can return all settings as an Object or one setting's
* value.
*/
var configure = function (name, value) {
    var result,
        args = arguments.length;

    if (args === 1) {

        if (!(name instanceof Object)) {
            result = settings[name];
        } else {
            util.each(name, function (value, key) {
                settings[key] = value;
            });
        }
    } else if (args === 2) {
        settings[name] = value;
    }

    return result === undefined ? settings : result;
};

// ================================================

// TODO: Figure out a better way to determine if
// this is being used from CLI or required in 
// another script.

var dir = process.argv[2];

if (dir && dir !== '--reporter') {
    go(dir);
} else {
    exports.init = init;
    exports.configure = configure;
    exports.go = go;
}